version: 2

models:
  - name: order_length
    description: "Time difference between order creation and order delivery"
    columns:
      - name: order_guid
        description: "Primary key for this table"
        tests:
          - unique
          - not_null
      - name: order_length
        description: "Length of the order in days"

  - name: repeat_users
    description: "To find users with more than one purchase"
    columns:
      - name: user_guid
        description: "Primary key for this table"
        tests:
          - unique
          - not_null
      - name: is_repeat_user
        description: "True if the user has 2+ orders, false if not"