version: 2

models:
  - name: int_number_of_orders_per_user
    description: "Number of orders placed by each user"
    columns:
      - name: user_guid
        description: "Primary key. Id of the user."
        tests:
          - unique
          - not_null
      - name: n_orders
        description: "Number of orders placed by the user"
        tests:
          - positive_values

  - name: int_repeat_users
    description: "To find users with more than one purchase"
    columns:
      - name: user_guid
        description: "Primary key for this table"
        tests:
          - unique
          - not_null
      - name: is_repeat_user
        description: "True if the user has 2+ orders, false if not"