version: 2

models:
  - name: facts_orders
    description: "Expanded model of order facts"
    columns:
      - name: order_guid
        description: "Primary key for this table. Id of the order."
        tests:
          - unique
          - not_null
      - name: user_guid
        description: "Id of the user placing the order"
        tests:
          - not_null
      - name: promo_guid
        description: "Promotion code used in the order"
      - name: created_at_utc
        description: "Timestamp when the order was created"
      - name: order_cost_usd
        description: "Cost of the order products"
      - name: shipping_cost_usd
        description: "Shipping costs"
      - name: order_total_usd
        description: "Total cost of the order"
      - name: tracking_id
        description: "Tracking id"
        tests:
          - has_tracking_id
      - name: shipping_service
        description: "Shipping service used"
      - name: estimated_delivery_at_utc
        description: "Estimated delivery time"
      - name: delivered_at_utc
        description: "Delivery time"
      - name: order_status
        description: "Status of the order"
      - name: delivery_address
        description: "Address to which the order is to be delivered"
      - name: order_length
        description: "Time between order creation and delivery"

  - name: facts_users
    description: "Expanded model of user facts"
    columns:
      - name: user_guid
        description: "Primary key. Id of the user."
      - name: first_name
        description: "First name"
      - name: last_name
        description: "Last name"
      - name: email
        description: "Email address"
      - name: phone_number
        description: "Phone number"
      - name: created_at_utc
        description: "Timestamp for user signup"
      - name: updated_at_utc
        description: "Timestamp for last info update"
      - name: address
        description: "Postal address"
      - name: user_ltv_usd
        description: "Total revenue generated since signup"
      - name: is_repeat_user
        description: "(Boolean) Has the user placed more than one order"
      - name: number_of_orders 
        description: "Total number of orders placed by the user"
        tests:
          - positive_values