version: 2

models:
  - name: facts_orders_user_level
    description: "Order information at the user level"
    columns:
      - name: order_guid
        description: "Primary key. Id of the order."
        tests:
          - unique
          - not_null
      - name: user_guid
        description: "Id of the user"
        tests:
          - not_null
      - name: promo_guid
        description: "Promotional code user in the order"
      - name: order_created_at_utc
        description: "Timestamp when the order was created"
      - name: order_cost_usd
        description: "Cost of the order products"
        tests: 
          - positive_values
      - name: shipping_cost_usd
        description: "Shipping costs"
        tests:
          - positive_values
      - name: order_total_usd
        description: "Total cost of the order"
        tests:
          - positive_values
      - name: tracking_id
        description: "Tracking id"
      - name: shipping_service
        description: "Shipping service used"
      - name: estimated_delivery_at_utc
        description: "Estimated delivery time"
      - name: delivered_at_utc
        description: "Timestamp when the order was delivered"
      - name: order_status
        description: "Status of the order"
      - name: user_first_name
        description: "First name of the user placing the order"
      - name: user_last_name
        description: "Last name of the user placing the order"
      - name: user_email
        description: "Email address of the user placing the order"
      - name: user_phone_number
        description: "Phone number of the user placing the order"
      - name: user_created_at_utc
        description: "Timestamp of user signup"
      - name: user_updated_at_utc
        description: "Timestamp of latest user info update"
      - name: delivery_address
        description: "Delivery address for the order"
      - name: order_length
        description: "Time between order placement and delivery"
      - name: user_ltv_usd
        description: "Total revenue generated by the user since signup"
        tests:
          - positive_values
      - name: is_repeat_user
        description: "(Boolean) Has the user placed more than one order"
      - name: number_of_orders 
        description: "Total number of orders placed by the user"
        tests: 
          - positive_values